### ISSUE TITLE
point to miltipoint example

### ISSUE THREAD

**Issue by hats0id** [ulikoehler/GuardMyWire#3]
Hello dear - thank you for this great script. Can you create example how to generate configs for wireguard server with point to multipoint connections. For example wireguard server on mikrotik and several android clients.

**Comment by ulikoehler** [comment]
Hi @hats0id  - Thank you :-) I just added the example in https://github.com/ulikoehler/GuardMyWire/blob/master/examples/PointToMultipoint.json
It would be great if you could review it and provide some feedback on whether this example is helpful.
Thanks, Uli
